spring:
    mvc:
        problemdetails:
            enabled: true

    mongodb:
        uri: mongodb://root:xuKBjW9sA3y4fcQ-HcO3750xrU0SLD2710mz587twPmH3heG@c0b0e72f-2ef7-413e-b1c1-aed03b7f9c7f.asia-south1.firestore.goog:443/db-eventhub?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
    port: 0

eureka:
    instance:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

app:
    storage:
        path: ${user.home}/.ijse/eventhub/events
